export const students = [
  {
    id: 1,
    lastName: 'Петухов',
    firstName: 'Родион',
    middleName: 'Сергеевич',
    age: '17',
    city: 'Брянск',
    group: 'ИС-21',
    attendance: 50,
    weeklyAttendance: [100, 50, 0, 100, 0],
    stats: { onTime: 12, late: 8, absent: 5 },
  },
  {
    id: 2,
    lastName: 'Комиссарова',
    firstName: 'Мадина',
    middleName: 'Александровна',
    age: '18',
    city: 'Брянск',
    group: 'ИС-21',
    attendance: 100,
    weeklyAttendance: [100, 100, 100, 100, 100],
    stats: { onTime: 25, late: 0, absent: 0 },
  },
  {
    id: 3,
    lastName: 'Шишкин',
    firstName: 'Матвей',
    middleName: 'Игоревич',
    age: '17',
    city: 'Брянск',
    group: 'ИС-21',
    attendance: 100,
    weeklyAttendance: [100, 100, 100, 100, 50],
    stats: { onTime: 24, late: 1, absent: 0 },
  },
  {
    id: 4,
    lastName: 'Уткин',
    firstName: 'Денис',
    middleName: 'Владимирович',
    age: '18',
    city: 'Брянск',
    group: 'ИС-21',
    attendance: 0,
    weeklyAttendance: [0, 0, 0, 0, 0],
    stats: { onTime: 0, late: 0, absent: 25 },
  },
  {
    id: 5,
    lastName: 'Кочеткова',
    firstName: 'София',
    middleName: 'Дмитриевна',
    age: '17',
    city: 'Брянск',
    group: 'ИС-21',
    attendance: 100,
    weeklyAttendance: [100, 100, 50, 100, 100],
    stats: { onTime: 23, late: 2, absent: 0 },
  },
  {
    id: 6,
    lastName: 'Михайлов',
    firstName: 'Тимофей',
    middleName: 'Андреевич',
    age: '18',
    city: 'Брянск',
    group: 'ИС-21',
    attendance: 50,
    weeklyAttendance: [50, 100, 0, 50, 100],
    stats: { onTime: 10, late: 10, absent: 5 },
  },
  {
    id: 7,
    lastName: 'Смирнова',
    firstName: 'Анастасия',
    middleName: 'Павловна',
    age: '17',
    city: 'Брянск',
    group: 'ИС-21',
    attendance: 50,
    weeklyAttendance: [0, 50, 100, 50, 0],
    stats: { onTime: 11, late: 9, absent: 5 },
  },
];

export function getStudentById(id) {
  return students.find((s) => s.id === Number(id));
}
